name: Java CI with Maven and Allure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'CHROME'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn -DbrowserName=${{ inputs.browserName || 'CHROME' }} verify

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: crazy-max/ghaction-github-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history